fix autofixer

diff --git a/scripts/goss/fix-all-in-order b/scripts/goss/fix-all-in-order
--- a/scripts/goss/fix-all-in-order
+++ b/scripts/goss/fix-all-in-order
@@ -7,7 +7,8 @@ o=$?
 if [[ $o -ne 0 ]]; then
     # TODO check if any of the errors have an autofix
     # if none do then exit non 0
-    echo "Something borked, trying to fix and then rerunning goss fixer"
+    set -e
+    echo "Something borked, trying to fix and then rerunning goss fixer (unless fixing fails)"
     s goss autofix-input <<<"$errs"
     s goss fix-all-in-order
 fi
